
title: "Curso de React com SOLID e Testes com Vitest"
description: "Aprenda React aplicando os princípios de SOLID e técnicas de testes com Vitest."
baseurl: "" # Subpath do site, se aplicável
url: "" # URL base do site (será configurada no ambiente de deploy)
repository: react-solid-vitest-course
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

show_downloads: true
theme: jekyll-theme-leap-day
# theme: merlot
# theme: midnight
# theme: minima
# theme: minimal
# theme: modernist
# theme: slate
# theme: tactile
# theme: time machine
